#
# @lc app=leetcode id=172 lang=python3
#
# [172] Factorial Trailing Zeroes
#

# @lc code=start
class Solution:
    def trailingZeroes(self, n):
        # zero generated by 2 and 5
        if n < 5:
            return 0
        ans = 0
        base = 5
        while n >= base:
            ans += n//base
            base *= 5
        return ans
        
if __name__ == '__main__':
    a = Solution()
    b = a.trailingZeroes(200)
    print(b)


# @lc code=end

